### ISSUE TITLE
unexpected 'end of template'

### ISSUE THREAD

**Issue by hilarex** [Thykof/template-pptx-jinja#2]
Hello ! 

When in try to run the example.py, after adding one jinja2 variable like {{ name }} in the 'template.pptx', I get : 
 
```python
Traceback (most recent call last):
  File "example.py", line 43, in <module>
    main()
  File "example.py", line 39, in main
    message = rendering.process()
  File “template-pptx-jinja/template_pptx_jinja/render.py", line 37, in process
    self._render_slide(slide)
  File “template-pptx-jinja/template_pptx_jinja/render.py", line 44, in _render_slide
    self._render_shape(shape)
  File “template-pptx-jinja/template_pptx_jinja/render.py", line 48, in _render_shape
    self._render_text_frame(shape.text_frame)
  File “template-pptx-jinja/template_pptx_jinja/render.py", line 64, in _render_text_frame
    self._render_paragraph(paragraph)
  File “template-pptx-jinja/template_pptx_jinja/render.py", line 68, in _render_paragraph
    self._render_run(run)
  File “template-pptx-jinja/template_pptx_jinja/render.py", line 78, in _render_run
    template = self.env.from_string(str(run.text))
  File "Python/3.8/lib/python/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "Python/3.8/lib/python/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "Python/3.8/lib/python/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected 'end of template'
```

I just git clone the project, open the "template.pptx", add {{ name }}, saved it and run python3 example.py

**Comment by Thykof** [comment]
Hello,

I have pushed into master some development instructions. Did you install the dependencies? 

Can you provide me with your pptx file so that I can reproduce the issue?

**Comment by nkyriazis** [comment]
It is probably an error due to how Powerpoint decides to distribute text across runs. I have been having several issues due to jinja variables, in the form of {{var}} are split across 3 runs. This lib operates on the run level, so it's very sensitive to the relevant intricacies and is likely to either fail to substitute or parse, altogether.

**Comment by ThomFri** [comment]
I think @nkyriazis is correct! I also encountered this problem recently and if you take a look at the runs, you can see that in many cases it looks like this:
run[0].text = "{{"
run[1].text = "varname }}"
So run[0].text alone can’t be rendered as “the template unexpectedly ends”.

It’s just a quick and dirty fix but you can try something like that (original idea comes from https://stackoverflow.com/a/57198891 and does therefore not require the template-pptx-jinja package):

```python
def render_presentation(replacements: dict, shapes, jinja_env):
    last_ok = True
    tmp_str = ""
    tmp_runs = []


    for shape in shapes:
        if shape.has_text_frame:
            text_frame = shape.text_frame
            for paragraph in text_frame.paragraphs:
                for run in paragraph.runs:
                    cur_text = run.text
                    tmp_str += cur_text
                    tmp_runs.append(run)
                    try:
                        rtemplate = jinja_env.from_string(tmp_str)
                        rendered_text = rtemplate.render(replacements)

                        for run in tmp_runs:
                            run.text = rendered_text
                            rendered_text = "" # overwrites text

                        tmp_str = ""
                        tmp_runs = []
                        last_ok = True
                    except Exception as e:
                        #could not finish, i.e. have to append!
                        last_ok = False


        if not last_ok:
            raise Exception(f'There must be an error in the template! Beginning near "{tmp_str}"')
```

**Comment by s3nn** [comment]
has this been fixed? Getting the same error

**Comment by Thykof** [comment]
> has this been fixed? Getting the same error

Hi, I think no, feel free to open a pull request. I'm not actively maintaining this repo.
